/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DeclarationsRouteImport } from './routes/declarations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeclarationsIdRouteImport } from './routes/declarations.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclarationsRoute = DeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclarationsIdRoute = DeclarationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeclarationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/declarations': typeof DeclarationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRoute
  '/declarations/$id': typeof DeclarationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/declarations': typeof DeclarationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRoute
  '/declarations/$id': typeof DeclarationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/declarations': typeof DeclarationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/users': typeof UsersRoute
  '/declarations/$id': typeof DeclarationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/declarations'
    | '/profile'
    | '/users'
    | '/declarations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/declarations'
    | '/profile'
    | '/users'
    | '/declarations/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/declarations'
    | '/profile'
    | '/users'
    | '/declarations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DeclarationsRoute: typeof DeclarationsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declarations': {
      id: '/declarations'
      path: '/declarations'
      fullPath: '/declarations'
      preLoaderRoute: typeof DeclarationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declarations/$id': {
      id: '/declarations/$id'
      path: '/$id'
      fullPath: '/declarations/$id'
      preLoaderRoute: typeof DeclarationsIdRouteImport
      parentRoute: typeof DeclarationsRoute
    }
  }
}

interface DeclarationsRouteChildren {
  DeclarationsIdRoute: typeof DeclarationsIdRoute
}

const DeclarationsRouteChildren: DeclarationsRouteChildren = {
  DeclarationsIdRoute: DeclarationsIdRoute,
}

const DeclarationsRouteWithChildren = DeclarationsRoute._addFileChildren(
  DeclarationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DeclarationsRoute: DeclarationsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
