name: Trade Vision EKS Build And Deploy
run-name: Deployment triggered for branch ${{ github.ref }} by @${{ github.actor }} with commit ${{ github.sha }} - ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: false
        default: ''
        type: choice
        options:
          - dev
          - test
          - production
      action:
        description: 'Select the action'
        required: false
        default: ''
        type: choice
        options:
          - ''
          - redeploy
      image_tag:
        description: 'Enter the image tag'
        required: false
        default: ''
  push:
    branches:
      - dev
      - test/v1
      - release/v1

jobs:
  build-and-deploy:
    runs-on: codebuild-trade-vision-runner-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      id-token: write
      issues: write
      contents: read
      packages: write
      checks: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Creating Environment Variables
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/dev' ]] || [[ "${{ inputs.action }}" == 'redeploy' && "${{ inputs.environment }}" == 'dev' ]]; then
            echo "SERVICE_NAME=trade-vision-dev" >> $GITHUB_ENV
            echo "K8S_DEPLOYMENT_NAME=dev-trade-vision" >> $GITHUB_ENV
            echo "DOCKER_IMAGE_REPO=255114580789.dkr.ecr.eu-central-1.amazonaws.com/trade-vision-dev" >> $GITHUB_ENV
            echo "env_x=dev" >> $GITHUB_ENV
            echo "space_x=dev" >> $GITHUB_ENV
            echo "namespace=dcs-online-dev" >> $GITHUB_ENV
            echo "CLUSTER_NAME=atez-dev-cluster" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == 'refs/heads/test/v1' ]] || [[ "${{ inputs.action }}" == 'redeploy' && "${{ inputs.environment }}" == 'test' ]]; then
            echo "SERVICE_NAME=trade-vision-test-v1" >> $GITHUB_ENV
            echo "K8S_DEPLOYMENT_NAME=trade-vision-test-v1" >> $GITHUB_ENV
            echo "DOCKER_IMAGE_REPO=255114580789.dkr.ecr.eu-central-1.amazonaws.com/trade-vision-test" >> $GITHUB_ENV
            echo "env_x=test-v1" >> $GITHUB_ENV
            echo "space_x=test-v1" >> $GITHUB_ENV
            echo "namespace=dcs-online-test" >> $GITHUB_ENV
            echo "CLUSTER_NAME=atez-dev-cluster" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == 'refs/heads/release/v1' ]] || [[ "${{ inputs